### ISSUE TITLE
Export to XLS failing with "Something went wrong while exporting."

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/build#102]
> I tried to export a form today, but keep getting an error message " Something went wrong while exporting. Please try again later. "

Reports from landsberg.florence@gmail.com (running 9e3b89b2e25b9d6070163ef8a1b9f7e972c4eca7) and muturiken@gmail.com.

**Comment by clint-tseng** [comment]
Fixed via PR #103; this is already run in staging and production.
