### ISSUE TITLE
https://build.opendatakit.org/ throws 404 on assets

### ISSUE THREAD

**Issue by florianm** [opendatakit/build#112]
Noticed just now that https://build.opendatakit.org/ does not load properly and 404s on its CSS / JS assets.
Worked fine yesterday, did anything change on your end or is that our network playing up?

**Comment by lognaturel** [comment]
I'm seeing it too, @florianm. I've been having what looks like the same problem in my local dev environment for a couple of revisions as well. Does it work for you locally?

**Comment by florianm** [comment]
@lognaturel I only ever used the hosted version, which worked yesterday (ca 2017-03-28 0800 UTC). What can I do to help?

**Comment by lognaturel** [comment]
I do believe @clint-tseng pushed a new version today and unfortunately, I think he's going to need to look at this one.

This is not ideal but if you need some way to just build a small form or demonstrate the tool, the staging server is up [here](https://staging.build.opendatakit.org/). It's running an older version with a completely different database, though, so won't have the forms you were working on.

**Comment by florianm** [comment]
@lognaturel thanks heaps!! I actually just need to create two new small enough forms, and with @clint-tseng 
s "save to .odkbuild" I can port that. Thanks to both of you for the quick turn-around and saving the day!

**Comment by clint-tseng** [comment]
It's back up. I still don't understand this issue.

**Comment by florianm** [comment]
@clint-tseng thanks for the fix! The very quick turnaround for this issue (being patched with an hour through the staging server and fixed within two hours) actually strengthens trust of my users in ODK. Much appreciated!
