### ISSUE TITLE
When opening a form, the bottom untitled number is used for the counter rather than the biggest

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/build#119]
1. Create a form with a few controls with sequential default names `untitledX` (e.g. untitled1, untitled2, untitled3)
1. Change the order of the controls such that the bottom one does not have the largest untitled number (e.g. untitled2, untitled3, untitled1)
1. Save the form and close it
1. Open the same form again
1. Add a new control

In the example case above, the new control's default name will be `untitled2`.

This is not a huge deal because users really shouldn't be keeping those default names but it's surprising behavior. Is it a big deal to iterate through and identify the LARGEST untitled suffix when first opening a form?

**Comment by clint-tseng** [comment]
Simple oversight.
