### ISSUE TITLE
Add ability to set message text for required prompts

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/build#122]
Let's say you define a form like this in XLSForm
<img width="515" alt="screen shot 2017-04-18 at 15 16 06" src="https://cloud.githubusercontent.com/assets/32369/25155471/f842979a-2449-11e7-8513-66fd27fd18d8.png">

The XML for that form is
```
<bind constraint=". &gt; 10"
      jr:constraintMsg="must be greater than 10" 
      jr:requiredMsg="cannot be blank" 
      nodeset="/basic/my_name" 
      required="true()" 
      type="int" />
```

In Collect, when if you leave the question blank, you get the `cannot be blank` message. And if you put in 9, you get the `must be greater than 10` message. 

Currently, Build doesn't support this interaction. What it does support is required (sets required=true()), length (sets a hardcoded constraint), invalid text (sets a constraint message), and constraint (sets a custom constraint). All this is to say, there is no way to set a required message and there should be.

**Comment by clint-tseng** [comment]
This all makes sense. Let's get it into the next release.

**Comment by clint-tseng** [comment]
Updated text since we _do_ have constraint prompts, just not required ones.
