### ISSUE TITLE
Save As for a new form doesn't work

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/build#130]
Create a new form, immediately Save As, I get "Could not save the form. Please try again in a moment."

Log shows `"POST /forms HTTP/1.1" 400`

**Comment by clint-tseng** [comment]
Seems like a you thing. Works perfectly for me. Is Postgres running? Try in `server/odkbuild_server.rb:105~107` interspersing some `puts` statements to get more debugging and see where the failure is? Also open Chrome inspector, go to the network pane, and tell me what the request payload says.

**Comment by lognaturel** [comment]
Huh. The check on `request_data[:controls].blank?` makes it impossible to save an empty form so you should also be getting that behavior, right? 

I like to save a blank document to give it a name before I get going. Is there a reason not to allow saving an empty form?

**Comment by clint-tseng** [comment]
Ah, a blank form. This is probably a subtle serialization behaviour change with the move from `json2` to native generation.

**Comment by clint-tseng** [comment]
Nope, must have always been the behaviour. But it's a one-liner.
