### ISSUE TITLE
Publicize native builds in online app.

### ISSUE THREAD

**Issue by clint-tseng** [opendatakit/build#133]
Point people at a download page for the native binaries from the online application. Two questions to resolve:

1. Where is best to put the link? I will figure this out.
2. Where to link to? Ideally somewhere within odk.org. @lognaturel or @yanokwa to figure this out.

**Comment by lognaturel** [comment]
@yanokwa @clint-tseng does https://opendatakit.org/downloads/download-category/build/ work for you?

**Comment by yanokwa** [comment]
It works for me in that it's consistent with the rest of the tools and lets us capture analytics.
