### ISSUE TITLE
xlsform export is missing labels

### ISSUE THREAD

**Issue by ellisuzuki** [opendatakit/build#137]
When exporting to XLSform format, the exported XLS file is missing the actual question labels!

**Comment by clint-tseng** [comment]
Oh shoot. This is my fault. Give me ten minutes.

**Comment by clint-tseng** [comment]
It looks like I neglected to properly restart the service when I upgraded it. Please try again now?

**Comment by ellisuzuki** [comment]
thanks. it's fixed now.
