### ISSUE TITLE
Describe the meaning of "Load Form from File"

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/build#147]
It's not clear what kind of file can be loaded in or what that feature is for. An explanation in the file chooser dialog would be very helpful. It would also be great to set the `accept` to `.build` files so users don't attempt to load Excel or XML documents.

**Comment by rockydcoder** [comment]
I want to take this up.

**Comment by rockydcoder** [comment]
On delving deeper in the issue, I discovered that a warning message does come up when one chooses the wrong type of file. But I have added a message so the user can see it before choosing anything. And I also set `accept` to `.odkbuild`
