### ISSUE TITLE
deviceid type not specified in exported XLSForm

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/build#148]
> I am using odkbuild 0.3.0. I have found repeadetly that in metada when I choose deviceid as 'Kind', the Type is not set to 'deviceid'. I had therefore to export the Form from Build as an XLSForm and set the Type, which is empty, manually to deviceid.

Source: https://groups.google.com/d/msg/opendatakit/KYMQwXq2Aoo/dMlcIQHpAAAJ

**Comment by clint-tseng** [comment]
Moving this into 0.3.1.

**Comment by clint-tseng** [comment]
Looks like this is a problem in build2xlsform specifically. XML export looks correct to my eye. Should be a quick fix; I have to get into that code for this release anyway.
