### ISSUE TITLE
Create role and database on db:create

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/build#153]
On a fresh checkout, Build requires developers to create a role and a database. It'd be ideal if this work was done by `rake db:create` because why not make the developer's life easier...

**Comment by clint-tseng** [comment]
Uhhh okay, but without a role how are you going to connect to the database?

**Comment by yanokwa** [comment]
Most rails apps that I use automagically let me setup the databases without manually having to create a role or a database. Is that a possibility here?

**Comment by lognaturel** [comment]
@yanokwa I bet it's because rails apps don't typically specify a db username in dev and instead use the default role matching the OS username.

**Comment by clint-tseng** [comment]
I think also many Rails apps default to SQLite for dev and MySQL/PostgresQL for prod, for which the SQLite db can just be invented from thin air. But I never liked the cavalier multi-db approach.

**Comment by lognaturel** [comment]
I don't know about that. All projects I've worked on have used postges for dev but just under the default username.

**Comment by clint-tseng** [comment]
In that case the create role step is redundant anyway, yes? You'd fill in existing credentials and skip creating a role. But we can't connect to the database to create a database unless there is a database. We can provide a separate shell script that uses shell commands to create the database, but I'm not sure how much time that's really saving?

**Comment by clint-tseng** [comment]
And even the `createdb` command then requires credentials, so then the shell script would need configuration unless the logged-in user has admin privs on postgres.

**Comment by yanokwa** [comment]
Maybe we can document how to get the DB up to match the config sample? It's something I always have to look up and it's a mild irritant.

```
CREATE ROLE odkbuild WITH LOGIN PASSWORD 'odkbuild';
CREATE DATABASE odkbuild WITH OWNER odkbuild;
GRANT ALL PRIVILEGES ON DATABASE odkbuild TO odkbuild;
\connect odkbuild
CREATE SCHEMA odkbuild;
ALTER SCHEMA odkbuild OWNER TO odkbuild;
GRANT ALL PRIVILEGES ON SCHEMA odkbuild TO odkbuild;
```

**Comment by clint-tseng** [comment]
oh wow, no wonder you find it irritating, you don't need nearly that much. just the first two lines will do. but yeah, i have no problem adding this to the readme, though i think it's pretty standard stuff for rails installs.
