### ISSUE TITLE
Add more form properties

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/build#154]
I love the return of form properties! And that return reminds me that http://xlsform.org/ref-table/ under the settings, as some form specific options that we should consider.

* `public_key` for [encrypted forms](https://opendatakit.org/help/encrypted-forms/)
* `submission_url`, mostly for Google Drive support, but folks do use it to submit to a different server than the form was downloaded from.
* `instance_name` to name submissions. There could be some clever UI where you build the name by choosing from the list of data names. 
* `version` for versioning. We might want to move the timestamp that build puts in the form id here and then give folks the change to override.

**Comment by clint-tseng** [comment]
I'm wrapping [a fix](https://forum.opendatakit.org/t/odk-build-offline-windows-0-32-2-questions/7107/4?u=clint) to `form_title` to account for Form Properties "Title on Device" into this ticket.

**Comment by clint-tseng** [comment]
Okay, so all of these also necessitate changes to Build's own XML output. For `version`, should that only be applied to `orx:version` (which we currently don't output at all), or also to `instance` `id`? And if we want to modify `id`, should the entirety of `id` be equal to `version` or just the timestamp suffix we currently apply? What if the user supplies an invalid version and this breaks `id`?

I maybe propose we implement the rest of these and kick `version` down the road a little bit, unless you have strong answers here.

**Comment by yanokwa** [comment]
I like the proposal of punting on version for now because it feels like a longer conversation. I've started a discussion with some of the key players here: https://forum.opendatakit.org/t/how-is-version-used-across-the-ecosystem/8964
