### ISSUE TITLE
The order of saved forms

### ISSUE THREAD

**Issue by Tomonori12** [opendatakit/build#182]
Hi there,

It is really great to contribute the ODK Build enhancement.  I am currently writing an ODK instruction book in Japanese, and i hope it will be finished in a couple of months.  

Anyway, just yesterday, I noticed that saved forms in my ODK Build account are not ordered by their form name.  I didn't have time to check if this is due to Japanese form names problem, and also how the ODK Build lines the saved forms up.  But it seems that the forms are sorted by the created time or the latest updated time.  I therefore think that it might be great to have a function to sort the saved forms by their name, created time and updated time.

Please kindly consider if putting this function can be useful.

Best,
Tomonori Hoshi
![upload](https://user-images.githubusercontent.com/22948249/28763981-f8a8f5bc-75fc-11e7-8529-7221e48c70f0.png)

**Comment by rockydcoder** [comment]
I can take this up. @clint-tseng , any pointers? Should there be a drop-down called _Sort_ which will have options like _Name_, _Created_, _Updated_, etc.?

**Comment by clint-tseng** [comment]
I think even just an initial version that simply client-side sorts everything by name ascending would be plenty. I don't recall whether the create/update dates are stored in an easily accessible way, and the audit table is I think not indexed for quick lookup of this sort.

**Comment by rockydcoder** [comment]
@clint-tseng , this issue can be closed now.
