### ISSUE TITLE
Field data names change to conflicting values after loading a form

### ISSUE THREAD

**Issue by timjholmes** [opendatakit/build#184]
BUG: After loading an old form, selecting some fields for editing causes the data name of that field to take the value of another somewhere else on the form.

STEPS: Open form... > select previously saved form > form loads with no red field errors > click one of the fields > field data name changes from the saved value to that of one of the fields further down the form, field goes red, conflicting data names warning appears.

NOTES
On a form composed of several groups
reproduced with the first (gps) and second (group) field so far

**Comment by timjholmes** [comment]
Google Chrome | 60.0.3112.90 (Official Build) (64-bit) (cohort: Stable)
Windows 10

**Comment by clint-tseng** [comment]
Hi; this sounds really problematic! Do you have a sample form you can attach that exhibits this problem? Thanks!

**Comment by timjholmes** [comment]
Oh dear. I'm sorry for wasting your time. I tracked the problem down to LastPass' autofill feature. I repeated my steps and the issue has not reappeared. The 'workaround' was to disable autofill for that page in my LastPass settings. 😊

**Comment by clint-tseng** [comment]
Ha! No need to apologize. I'm glad you figured it out, and it's definitely a good laugh—so, thank you for that!
