### ISSUE TITLE
Select one field list logic error even if no follow-up question is specified

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/build#186]
Create a group. Place a select one in the group. Toggle the "display on one screen" checkbox on the group.

**Comment by florianm** [comment]
@lognaturel I'm getting the same error, however upload to ODK-A still works, and ODK Validate also finds no problem. ODK Build shows the select one field in red with the following warning:

```
[ ] Follow-up Question
Ask if the response is:
(inactive, but a value is selected)
    Because this control is within a single-screen group (field list), any expressions that reference other fields in the same group will not work.
```

**Comment by florianm** [comment]
Found a fix: dragging the falsely red-flagged "select one" to the end of the group will turn off the warning. Dragging it back to the original position will preserve the "ok" status.

The warning itself is legit - follow-up fields will not work inside a "keep on one screen" group as both the select one and the follow up fields render together (makes sense to me).

**Comment by clint-tseng** [comment]
Okay, the issue here is that it genuinely is supposed to be a warning and not an error, but right now there's no visual distinction between the two.

**Comment by florianm** [comment]
Currently, the warning around "follow up question" and the widget colour disappear only after the widget has been dragged around. It would be great if it would disappear when the "follow up question" checkbox is unchecked.
