### ISSUE TITLE
Required text cannot be saved

### ISSUE THREAD

**Issue by florianm** [opendatakit/build#190]
https://build.opendatakit.org/ running 532f8f781d070b6e82a2cf0ca7b3d454ec0ec7a3

The "Required Text" cannot be saved and is lost as soon as another widget is selected.

**Comment by clint-tseng** [comment]
Hmmm. It works for me. Perhaps the repro is a bit more specific than that?

**Comment by florianm** [comment]
@clint-tseng thanks for the quick reply! Here's the troublemaker:

[Track or Treat 0.35.odkbuild.zip](https://github.com/opendatakit/build/files/1384178/Track.or.Treat.0.35.odkbuild.zip)

I can't seem to save a "Required Text" for e.g. /data/details/species or /data/nest/disturbed or any of the other fields.

All the failing fields are within groups. Outside groups, required text seems to stick.

**Comment by florianm** [comment]
Thanks for the fix! Is there a timeline for the rollout to build.opendatakit.org?

Looking at [ODK Build](https://build.opendatakit.org/) running version 532f8f781d070b6e82a2cf0ca7b3d454ec0ec7a3, this bug still exists.

Repro: enter required text for required field inside a group, select other field, select first field again, required text is gone.
