### ISSUE TITLE
Groups with corresponding instance node should have ref attribute linking the two

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/build#195]
If a `group` has a corresponding node in the `instance`, it should have a `ref` attribute: https://opendatakit.github.io/xforms-spec/#groups

Build doesn't add one which can cause problems in cases like nested groups: https://github.com/opendatakit/javarosa/issues/218#issuecomment-345206714

**Comment by clint-tseng** [comment]
Okay, I'd like to fix this but I don't fully understand the implications here. Build exclusively uses `nodeset` bindings, it _never_ uses `ref` currently. So if groups suddenly get a `ref` notation, does that impact the present explicit absolute `nodeset` bindings?

And, which groups should get `ref`s? All? Only the implicit ones that wrap repeats?

**Comment by lognaturel** [comment]
In ODK XForms `bind` and `nodeset` are used interchangeably as far as I can tell. In the specific case of groups I'm 100% sure that is the case -- you could use either.

I think that in Build all groups have a corresponding node in the `instance`, right? There's no way to specify a group and only have it in the body? If that's indeed the case then all groups generated by Build should be linked to the node they correspond to in the instance. `ref` would be consistent with pyxform but `nodeset` will have the same effect.

**Comment by clint-tseng** [comment]
Okay—I'll add this in a branch and we can test the resulting forms in Collect to double check this. I'm still fairly convinced this change will somehow break everything.

**Comment by clint-tseng** [comment]
You are annoying sometimes, @opendatakit-bot. :)

**Comment by clint-tseng** [comment]
fixed in #213
