### ISSUE TITLE
Cannot export to XLSForm

### ISSUE THREAD

**Issue by grzesiek2010** [opendatakit/build#201]
Trying to export a  form to XLSForm I see a message:

> Something went wrong while exporting. Please try again later.

The problem has been also reported on the forum: https://forum.opendatakit.org/t/download-excel-format-from-odk-build/12739

I tried different forms and it doesn't work, even pretty basic one like:

```
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa">
  <h:head>
    <h:title>Untitled Form</h:title>
    <model>
      <instance>
        <data id="build_Untitled-Form_1524041823">
          <meta>
            <instanceID/>
          </meta>
          <text/>
        </data>
      </instance>
      <itext>
        <translation lang="English">
          <text id="/data/text:label">
            <value>text</value>
          </text>
        </translation>
      </itext>
      <bind nodeset="/data/meta/instanceID" type="string" readonly="true()" calculate="concat('uuid:', uuid())"/>
      <bind nodeset="/data/text" type="string"/>
    </model>
  </h:head>
  <h:body>
    <input ref="/data/text">
      <label ref="jr:itext('/data/text:label')"/>
    </input>
  </h:body>
</h:html>
```

**Comment by grzesiek2010** [comment]
The issue occurs from time to time because:
[The server that Build is on is a little small and so the XLS convertor keeps crashing](https://forum.opendatakit.org/t/download-excel-format-from-odk-build/12739/5?u=grzesiek2010)

Restarting the server should help.

**Comment by yanokwa** [comment]
Fixed by upgrading the server to something beefier.

**Comment by chibsta** [comment]
Hi,

I recently installed ODK Build from source (https://github.com/opendatakit/build) on my Linux desktop (Ubuntu 18.04). The machine has plenty of resources - 24gb RAM, i5 quad core. Everything works swimmingly until I try to "Export to XLSForm". The export fails and the error and stacktrace below appear in the server logs:

NoMethodError: undefined method `join' for #<String:0x0000557faf0a36e0>
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/sinatra-1.2.6/lib/sinatra/showexceptions.rb:37:in `rescue in call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/sinatra-1.2.6/lib/sinatra/showexceptions.rb:20:in `call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/sinatra-1.2.6/lib/sinatra/base.rb:1272:in `block in call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/sinatra-1.2.6/lib/sinatra/base.rb:1303:in `synchronize'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/sinatra-1.2.6/lib/sinatra/base.rb:1272:in `call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/rack-1.6.5/lib/rack/static.rb:124:in `call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/warden-1.0.6/lib/warden/manager.rb:35:in `block in call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/warden-1.0.6/lib/warden/manager.rb:34:in `catch'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/warden-1.0.6/lib/warden/manager.rb:34:in `call'
	/media/storage/install/build-master/server/model/connection_manager.rb:16:in `call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/rack-1.6.5/lib/rack/tempfile_reaper.rb:15:in `call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/rack-1.6.5/lib/rack/lint.rb:49:in `_call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/rack-1.6.5/lib/rack/lint.rb:37:in `call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/rack-1.6.5/lib/rack/showexceptions.rb:24:in `call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/rack-1.6.5/lib/rack/chunked.rb:54:in `call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/rack-1.6.5/lib/rack/content_length.rb:15:in `call'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/thin-1.7.0/lib/thin/connection.rb:53:in `process'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/thin-1.7.0/lib/thin/connection.rb:39:in `receive_data'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/eventmachine-1.2.1/lib/eventmachine.rb:194:in `run_machine'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/eventmachine-1.2.1/lib/eventmachine.rb:194:in `run'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/thin-1.7.0/lib/thin/backends/base.rb:73:in `start'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/thin-1.7.0/lib/thin/server.rb:162:in `start'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/rack-1.6.5/lib/rack/handler/thin.rb:19:in `run'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/rack-1.6.5/lib/rack/server.rb:286:in `start'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/rack-1.6.5/lib/rack/server.rb:147:in `start'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/rack-1.6.5/bin/rackup:4:in `<top (required)>'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/bin/rackup:23:in `load'
	/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/bin/rackup:23:in `<main>'

and the message: **"Something went wrong while exporting. Please try again later."** in the browser

I have tried stopping and restarting the server several times. The server version given at startup is:

/media/storage/install/build-master/vendor/bundle/ruby/2.5.0/gems/thin-1.7.0/lib/thin/server.rb:107: warning: constant ::Fixnum is deprecated
**Thin web server (v1.7.0 codename Dunder Mifflin)**

When I open the same survey on https://build.opendatakit.org/ I can export the survey to XLSForm. Kindly assist.

Regards,

**Comment by clint-tseng** [comment]
so, i'm not sure why you're getting such a spectacular error message, but my first question is: are you also running the build2xlsform server https://github.com/opendatakit/build2xlsform ?

**Comment by chibsta** [comment]
Hi Clint, 

Thanks for the quick revert. I am not running the build2xlsform server. There was no reference to it on the build installation instructions (or I missed it). The instruction look quite straightforward. Will give it a go! 

Thanks and regards,

**Comment by clint-tseng** [comment]
there was no reference to it. there should be. :)

i'll fix it soon, thanks for pointing that out! we don't get a lot of people trying to install/run the build web server on their own.

**Comment by chibsta** [comment]
Thanks Clint setting up and running the build2xlsform server sorted out the issue! By the way I noted that your documentation notes support for NodeJs v5 or 6. I installed the latest nodejs  (v12.1.0) on Ubuntu and all seems to work well.

**Comment by clint-tseng** [comment]
okay, thanks for the note! we know it works on 8 and 10 as well; i'll adjust the note to read "5 or higher" or something along those lines.

**Comment by yanokwa** [comment]
@chibsta I'm curious! Why are you running your own build web server?

**Comment by chibsta** [comment]
Hi @yanokwa! I am running my own build server primarily for 2 reasons:

1. I noted that the desktop version is only available for Windows and Mac (unless I missed something). I prefer to work on a Linux box and so I had to build from source, pardon the pun! I do travel quite a bit and some areas I go to do not have the best network coverage, so at some stage I need to work offline.

2. There's a requirement in my organization to have all developments/data hosted on the company's servers so I needed to make that transition to comply. I've earlier moved the Aggregate and Enketo setup to our data center. Now that I know how to run the build server on my machine I can now satisfy this requirement as well.

Hope this makes sense?!

**Comment by yanokwa** [comment]
It makes perfect sense. Thanks for providing that extra detail!

Since you are a dev, you might want to look at designing your forms with XLSForm and using [pyxform](https://github.com/xlsform/pyxform) on the command line to convert to XML. You'll likely still need Build for your users, but you'll have another option :)

**Comment by chibsta** [comment]
I normally just use Build to get me going and then do most of the tweaking with XLSForm (hence the need for build2xlsform). I have not yet used pyxform, have been using the online ODK coverter. Will give it a go, thanks!
