### ISSUE TITLE
Replace relevance with "Show question if"

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/build#203]
Users don't know what relevance means. It would also really help to show an example (something simple like `/data/age > 10` -- only show this question if the question named `age` has a value above 10).

See https://forum.opendatakit.org/t/guide-me-on-setting-up-skips-on-build/13739 for a user who doesn't know where to start.

**Comment by lognaturel** [comment]
That makes sense! I do think there's a nice opportunity to make an important feature easier to discover and use. It also leads to a lot of questions on the forum.

Of course if you're not sure about the wording, I just wanted to put some suggestions out!

**Comment by clint-tseng** [comment]
resolved in #216.
