### ISSUE TITLE
XLSForm export has questions with empty parens in relevant column

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/build#208]
I'm not sure how this happens, but https://forum.opendatakit.org/t/collect-error-problem-with-display-condition-for-node/14448/10 has a screenshot with an example.

https://forum.opendatakit.org/t/my-forms-wont-send-because-all-the-columns-are-missing/15390/7 is a related issue.

**Comment by yanokwa** [comment]
https://forum.opendatakit.org/t/help-with-invalid-xform-error-message-when-trying-to-convert-xls-to-xform-using-xlsform-online/17187 is another example of the issue.

**Comment by clint-tseng** [comment]
i believe https://github.com/opendatakit/build2xlsform/pull/5 fixes this issue
