### ISSUE TITLE
LetsEncrypt reload not working?

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/build#211]
Users reported certs expired on Dec 14th. I checked the crontab and ran that command as is, then without `--quiet` (shown below)

```
$ /usr/local/share/letsencrypt/env/bin/letsencrypt renew  --post-hook "systemctl reload nginx"
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/build.opendatakit.org.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/build.opendatakit.org/fullchain.pem (skipped)
No renewals were attempted.
No hooks were run.
```

That output suggested that the certs were up-to-date, so I figured the problem might be nginx, so I ran the following: `systemctl reload nginx` and that seemed to fix all the things.

My guess is that the post-hook is broken?

**Comment by clint-tseng** [comment]
looks like i don't have access to this server anymore either.

**Comment by yanokwa** [comment]
Just added you to this server and staging. If it doesn't work, find me on Slack.

**Comment by clint-tseng** [comment]
i'm not sure how to actually work on this without seeing the broken output so i've scheduled a reminder on jan 15 next year to take a look.

**Comment by clint-tseng** [comment]
i don't know what happened here but it seems to have been a one-time thing. closing for now.
