### ISSUE TITLE
Select > options > bulk edit > save to preset broken

### ISSUE THREAD

**Issue by florianm** [opendatakit/build#22]
From the modal bulk edit dialog, the save to preset function does not have any effect, i.e., the saved preset does not show up in the (always empty) 'load from saved preset' dropdown.

**Comment by clint-tseng** [comment]
Hm — this feature is working for me. What are the steps involved to recreate this problem? Thanks.

**Comment by florianm** [comment]
@clint-tseng just hopping onto the ODK band wagon again - I'm now able to save 10 presets, but it appears I can't save more. 

Saving presets is immensely useful to keep multiple forms sharing the same dropdowns - thanks for the feature in the first place!

If possible, keeping more than ten presets would be super handy. Uploading presets from CSV would reduce the amount of typing, and exporting to CSV would help backing them up.

**Comment by clint-tseng** [comment]
Whoa, that's weird. I didn't put the number 10 in there anywhere. Is it 10 preset sets or 10 entries in one preset? Mind exporting an example form and emailing it to me?

**Comment by lognaturel** [comment]
@florianm @clint-tseng Did you get a chance to share an example for troubleshooting?

**Comment by florianm** [comment]
@lognaturel @clint-tseng sorry for the delay - seems to work on my end now.
I've got 22 select presets in one form.
