### ISSUE TITLE
uninitialized constant DB

### ISSUE THREAD

**Issue by subu1979** [opendatakit/build#37]
I have installed the following
1) ODKbuild
2) Tokyo Tyrant

When i'am executing from browser http://localhost:9393 i'am getting the following error

![screen shot 2014-05-22 at 3 45 46 pm](https://cloud.githubusercontent.com/assets/3286581/3052372/b5e8eb74-e199-11e3-8d7d-e235f8a18321.png)

**Comment by lognaturel** [comment]
@subu1979 Do you still need to run Build locally and if so, are you still getting this error?

**Comment by jorgepsendziuk** [comment]
anyone got this to work? i'm stuck in that part too. 
ubuntu server (14.04)
ruby (2.4.0) &
tokyotyrant (1.13)

**Comment by clint-tseng** [comment]
Make sure y'all install the correct gem; it's `ruby-tokyotyrant`, not `tokyotyrant`.

**Comment by clint-tseng** [comment]
This is no longer relevant, as Tokyo Tyrant has been deprecated entirely. Hopefully the new Postgres backing is much easier for y'all to work with!
