### ISSUE TITLE
Underlying values of selects should allow hyphens/dashes and be constrained to 32 chars

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/build#45]
Underlying values of selects should allow hyphens/dashes because it's human-friendly and a JavaRosa-compliant way to name values. 

Build should not allow values greater than 32 characters because that will trigger a warning in JavaRosa (see [source code](https://github.com/opendatakit/javarosa/blob/master/core/src/org/javarosa/xform/parse/XFormParser.java#L1189)).

Long term, @MartijnR is documenting the [ODK form specifications](github.com/opendatakit/odk-xform-spec). Once he's finished, then we can make sure Build is compliant. 🎉🍾👏🏾

**Comment by florianm** [comment]
+1 for dashes!

**Comment by clint-tseng** [comment]
How about periods? Those are valid per XML spec.

**Comment by yanokwa** [comment]
Good question. I've tested a small sample form with periods in column names and in calculations it works in an end-to-end test using XLSForm and Collect and Aggregate.

I think we should add period support to control and group names as well. @clint-tseng, can you file that as a separate issue?

**Comment by clint-tseng** [comment]
Separate? It's trivial to include in this ticket.

**Comment by clint-tseng** [comment]
Should just be part of #46, no?

**Comment by florianm** [comment]
Thanks @clint-tseng, this will make my data ingestion much easier, as it allows field names to match exactly.

**Comment by florianm** [comment]
@lognaturel @clint-tseng apologies for the poke - is this feature live yet at build.opendatakit.org (showing version 0.90)? I can currently use underscores in underlying values for select one widgets, but no dashes or dots.

**Comment by clint-tseng** [comment]
hey @florianm: sorry about the delay; it should be working now.

**Comment by florianm** [comment]
@clint-tseng thanks heaps!
