### ISSUE TITLE
More consistent property naming across controls and groups.

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/build#47]
Controls use the `Data Name` and `Caption Text` while Groups use the `Name` and `Label` naming. We should have a discussion and pick one.

**Comment by clint-tseng** [comment]
I'm in favour of `Data Name`. I'm ambivalent about `Caption Text` vs `Label`.

**Comment by yanokwa** [comment]
I like `Data Name` and `Data Label` because it matches what is done in XLSForm. We should also update the hint text.

{Data,Group} Name - The name of the column in the exported data
{Data,Group} Label - The text that is presented to the user filling the form
