### ISSUE TITLE
Change prompt color to red when relevance in a field-list will not work

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/build#48]
When there are relevance expressions that refer to other fields in the same group, Build correctly shows a warning in the advanced part of the UI. 
![screen shot 2016-12-07 at 09 20 42](https://cloud.githubusercontent.com/assets/32369/20961877/e7c3e5b6-bc5e-11e6-8bf4-7418414cafdb.png)

I think Build should also turn the color of the prompt red (just like it does when the data name of the prompt is invalid). It is important to show this warning more clearly because the behavior of the form in Collect will be subtle and hard for novice users to detect.
![screen shot 2016-12-07 at 09 23 38](https://cloud.githubusercontent.com/assets/32369/20961891/fcfb6fda-bc5e-11e6-8901-c69264b5dc7d.png)

**Comment by clint-tseng** [comment]
This bug is fixed by PR #52.
