### ISSUE TITLE
Only show data loss warning when there are unsaved changes

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/build#81]
#### Problem description
The data loss warning ("Are you sure? You will lose unsaved changes to the current form.") is always shown when clicking on File > Open Form... even if changes were just saved. It would be better if it were only shown when there are changes to lose.

#### Steps to reproduce the problem
1. Edit a form
1. Save the form
1. Click on File > Open Form...
1. The "Are you sure? You will lose unsaved changes to the current form." dialog appears even though changes were just saved

#### Expected behavior
Only display the data loss warning if there were changes since the last save.

**Comment by clint-tseng** [comment]
Resolved with today's release.
