### ISSUE TITLE
Add in-app link to user survey

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/build#83]
It would be ideal to get feedback from current users to inform priority setting. One idea to solicit that feedback would be to prompt users with a modal to fill out an optional survey with a few questions about their experience and priorities. This would run for a limited time and ideally could involve some kind of cookie so the same person isn't prompted over and over again.

**Comment by clint-tseng** [comment]
@lognaturel here's a first draft at an intercept survey: https://docs.google.com/a/dontexplain.com/forms/d/1xghlVesmb3z3ZHR7aUlbS8uDvxBy2EPb08HisD13gD8/edit

**Comment by lognaturel** [comment]
Talked to @yanokwa about your conversation and made a couple of small wording changes. Looks good to go!
