### ISSUE TITLE
Inclusive tick boxes of text length can be hidden?

### ISSUE THREAD

**Issue by Tomonori12** [opendatakit/build#90]
Hi.  I found a great improvement on ODK Build version 9.0.  It was awesome, really. 

Here, I have a small suggestion to improve user experiences for text length setting.  In current ODK Build version 9.0, there are "inclusive" tick boxes appearing just below the entry fields of minimum and maximum.  However, the inclusive function is not responding, and indeed it might be unnecessary entries.  Because the text is not like a numeric number and no need to precisely consider "inclusive" or "exclusive".  To avoid any confusion, if it's possible, it may be better to hide the function of inclusive from the text length setting. 

Thanks.

**Comment by clint-tseng** [comment]
Agreed! I'd meant to do this but forgot. I'll mark this as a quick win for contributors that come into the project. Thanks for the report!

**Comment by daveycrockett** [comment]
I'd like to take a stab at this one if that's alright?  Looking to familiarize myself with the project.  Are you looking to fix this simply with CSS targeting to hide the controls, or something a little deeper into the control.js or index.erb?

**Comment by clint-tseng** [comment]
Yeah, my approach would have almost certainly just been CSS. Go for it!

**Comment by daveycrockett** [comment]
PR opened! https://github.com/opendatakit/build/pull/105

**Comment by clint-tseng** [comment]
This is on master and shall be deployed soon.
