### ISSUE TITLE
When restarting the Build, added languages were not shown in the View menu. 

### ISSUE THREAD

**Issue by Tomonori12** [opendatakit/build#91]
Hi there.

Thanks for developing the ODK Build.  I found an issue on the multi language setting.  When I create a form in more than two languages, the language can be added at the "manage translation" of the Edit menu.  I then can switch a displayed language at the View menu.  Let's say, I can add/switch English to Japanese.  These functions work fine.  

However, once i close the browser and sign in the ODK Build again, and open the saved form with multiple languages, the View menu only shows "English" on the list.  To solve this issue, I have to add Japanese language at the "manage translation" menu every time in a blank form page before i start form editing.  

Also, if i delete English from the translation list, it comes back every time when i restart the browser.  I think this happens because English is considered as the default language in the ODK Build.  I don't know if improving this issue is hard, but it should be helpful for ones creating forms with multiple languages. 

Thanks.

**Comment by clint-tseng** [comment]
Understood! I'll take a look at this one soon, thanks for the report!
