### ISSUE TITLE
Use short git hash for identifying version in About menu

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/build#95]
[This code](https://github.com/opendatakit/build/blob/master/circle.yml#L18) sets the build revision to the hash code of the latest commit (read more about commit hash codes [here](https://blog.thoughtram.io/git/2014/11/18/the-anatomy-of-a-git-commit.html#whats-up-with-those-long-revision-names)). This is visible from the Help > About menu.

This 40-character string can be overwhelming to someone who doesn't know what it is. Use instead the short 7-character hash by taking a substring of the full hash. For example, `94149e02501aad515401521159e9625a7108a558` should be displayed as `94149e0`.

**Comment by shaktilucifer** [comment]
I would like to give this a go if it's alright. Thanks

**Comment by lognaturel** [comment]
@shaktilucifer Yes, please!

**Comment by shaktilucifer** [comment]
@lognaturel I am seem to be having an issue when i run the build locally. The revision number says "an unknown revision"  instead of a 40 character string. Any idea if I am missing something ? Thanks!

**Comment by lognaturel** [comment]
Ah, I see, that hash comes from CircleCI. @clint-tseng what's your recommendation for trying this out?

**Comment by clint-tseng** [comment]
* This is the line that prints the SHA: https://github.com/opendatakit/build/blob/master/server/views/index.erb#L352
* Searching the codebase for that method name reveals: https://github.com/opendatakit/build/blob/master/server/asset_manager.rb#L10
* Looking a couple lines down, we see where the SHA comes from: https://github.com/opendatakit/build/blob/master/server/asset_manager.rb#L17

**Comment by shaktilucifer** [comment]
Ah . Great! thanks for the help guys. Let me test this out.

**Comment by saraswatmanu** [comment]
Anyone still on it? Can I give it a try?

**Comment by clint-tseng** [comment]
It's been a while—I'd say give it a shot.

**Comment by extremelypenguin** [comment]
hey, it seems that no one is doing this right now since the last post was a long time ago. Is this issue still open?

**Comment by clint-tseng** [comment]
Hi Penguin! Sadly, yes. Want to give it a try? :)

**Comment by extremelypenguin** [comment]
@clint-tseng I'm a bit confused as to where the hash is being generated. From my understanding, in [https://github.com/opendatakit/build/blob/master/circle.yml#L18](), the hash is `url`. Is this correct?

**Comment by clint-tseng** [comment]
You're in the right file; it's this line that does it: https://github.com/opendatakit/build/blob/master/circle.yml#L11

Locally, if you just want the file to test, you can just do `git rev-parse HEAD > .build_rev`.

**Comment by extremelypenguin** [comment]
@clint-tseng After some Googling it seems that it is impossible to concatenate strings via YAML, so we need to go find where this YAML is parsed so we can concatenate there. Where is it located? I've looked through all the files in the repo and I haven't found any instance where circle.yml is called.

**Comment by clint-tseng** [comment]
So, we don't want to change the build procedure at all, nor do we want to change the contents of `.build_rev` on-disk. We just want to truncate the output itself; you can find that line of code [here](https://github.com/opendatakit/build/blob/master/server/views/index.erb#L427).

**Comment by extremelypenguin** [comment]
@clint-tseng sooo if my thinking is correct it would be something like:

``<script>``
  ``    function var1() {``
   ``  document.getElementById('text').innerHTML = "document.getElementById('text').innerHTML.slice(0,6)"``
``}

       ``window.onload = var1;``
``<script>``

``<p id = "text">``
          ``You are running <%= AssetManager.build_rev %>``
``</p>``

**Comment by moogacs** [comment]
@lognaturel  is this issue still open ?
because https://github.com/opendatakit/build/blob/master/circle.yml#L18 not available

**Comment by clint-tseng** [comment]
hi: yes, this issue is still open. that file is now here: https://github.com/opendatakit/build/blob/master/.circleci/config.yml
