### ISSUE TITLE
Photo submit error

### ISSUE THREAD

**Issue by mpwstaff** [opendatakit/build#97]
Hi,
I found an issue that might lie within either Collect or Build, but I'm leaning toward Build because it only affects recently-created forms.
I get the following message when trying to submit a form containing photos in ODK Collect:

"Picasa Error: 501 Not Implemented. Insert is no longer supported."

This only happens with a new copy of the form which was exported to XLS from ODK Build on 2/24. An XLS copy of the same form exported in mid-January is working normally. I replicated this with two different forms on Collect 1.4.12 and 1.4.16. One of the forms had not been edited at all since the older copy was exported.

Thanks

**Comment by clint-tseng** [comment]
This is indeed a Collect issue: https://github.com/opendatakit/collect/issues/442
You'll want to track this ticket for progress updates: https://github.com/opendatakit/collect/issues/367
